baseurl      = "https://nicktehrany.github.io"
title        = "Nick Tehrany"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 6

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "I'm currently a MSc computer science student, and my main interests are in Storage Systems and Technologies, Operating Systems, Distributed Systems, and Computer Architecture."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = false

  # Metadata mostly used in document's head
  description = "My website with my past and ongoing work."
  keywords = "homepage "
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "light"

  footerLeft = "Contact: tehrany.nick@gmail.com"

[taxonomies]
    category = "categories"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Nick Tehrany"
    keywords = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "gst@nty: $ cd ~"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "publications"
    name       = "Publications"
    url        = "/publications"
    weight     = "1"

  [[menu.main]]
    identifier = "awards"
    name       = "Awards"
    url        = "/awards"
    weight     = "3"

  [[menu.main]]
    identifier = "talks"
    name       = "Talks"
    url        = "/talks"
    weight     = "2"

  [[menu.main]]
    identifier = "notes"
    name       = "Notes"
    url        = "/notes"
    weight     = "4"

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
    weight     = "5"

  [[params.social]]
    name = "github"
    url  = "https://github.com/nicktehrany"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/nicktehrany/"
