baseurl      = "https://nicktehrany.github.io"
title        = "Nick Tehrany"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 6

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "My website with all my current & past work and projects."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = false

  # Metadata mostly used in document's head
  description = "My website with what I'm currently working on."
  keywords = "homepage, blog"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"

[taxonomies]
    category = "categories"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Nick Tehrany"
    keywords = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cd nicktehrany"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "publications"
    name       = "Publications"
    url        = "/publications"

  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/projects"

  [[menu.main]]
    identifier = "notes"
    name       = "Uni Notes"
    url        = "/notes"

  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts"

  [[params.social]]
    name = "github"
    url  = "https://github.com/nicktehrany"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/nicktehrany/"
