baseurl      = "https://github.com/nicktehrany/nicktehrany.github.io"
title        = "Nick Tehrany"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Website with all my current and past work."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My website with what I'm currently working on."
  keywords = "homepage, blog"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Nick Tehrany"
    keywords = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "nick's website"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

  [[menu.main]]
    identifier = "thesis"
    name       = "Thesis"
    url        = "/posts"

  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/posts"

  [[menu.main]]
    identifier = "notes"
    name       = "Uni Notes"
    url        = "/posts"

  [[params.social]]
    name = "github"
    url  = "https://github.com/nicktehrany"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/nicktehrany"