name: CI
on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.74.3"
      
      - name: Setup themes
        run: |
          git submodule update --init --recursive
          cd themes/hello-friend-ng
          git checkout 4c3a69eaa6b3747fc5344fa4e1311459d6e0b88f
  
      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: nicktehrany/nicktehrany.github.io
          publish_dir: ./public
          user_name: nicktehrany
          commit_message: ${{ github.event.head_commit.message }}
          user_email: nicktehrany1@gmail.com
          publish_branch: master
